ALTER EXTENSION postgis_topology ADD cast(topogeometry as geometry);
ALTER EXTENSION postgis_topology ADD function _asgmledge(integer,integer,integer,geometry,regclass,text,integer,integer,text,integer);
ALTER EXTENSION postgis_topology ADD function _asgmlface(text,integer,regclass,text,integer,integer,text,integer);
ALTER EXTENSION postgis_topology ADD function _asgmlnode(integer,geometry,text,integer,integer,text,integer);
ALTER EXTENSION postgis_topology ADD function _st_addfacesplit(character varying,integer,integer,boolean);
ALTER EXTENSION postgis_topology ADD function _st_adjacentedges(character varying,integer,integer);
ALTER EXTENSION postgis_topology ADD function _st_mintolerance(character varying,geometry);
ALTER EXTENSION postgis_topology ADD function _st_mintolerance(geometry);
ALTER EXTENSION postgis_topology ADD function addedge(character varying,geometry);
ALTER EXTENSION postgis_topology ADD function addface(character varying,geometry,boolean);
ALTER EXTENSION postgis_topology ADD function addnode(character varying,geometry);
ALTER EXTENSION postgis_topology ADD function addnode(character varying,geometry,boolean,boolean);
ALTER EXTENSION postgis_topology ADD function addtopogeometrycolumn(character varying,character varying,character varying,character varying,character varying);
ALTER EXTENSION postgis_topology ADD function addtopogeometrycolumn(character varying,character varying,character varying,character varying,character varying,integer);
ALTER EXTENSION postgis_topology ADD function addtosearchpath(character varying);
ALTER EXTENSION postgis_topology ADD function asgml(topogeometry);
ALTER EXTENSION postgis_topology ADD function asgml(topogeometry,regclass);
ALTER EXTENSION postgis_topology ADD function asgml(topogeometry,regclass,text);
ALTER EXTENSION postgis_topology ADD function asgml(topogeometry,text);
ALTER EXTENSION postgis_topology ADD function asgml(topogeometry,text,integer,integer);
ALTER EXTENSION postgis_topology ADD function asgml(topogeometry,text,integer,integer,regclass);
ALTER EXTENSION postgis_topology ADD function asgml(topogeometry,text,integer,integer,regclass,text);
ALTER EXTENSION postgis_topology ADD function asgml(topogeometry,text,integer,integer,regclass,text,integer);
ALTER EXTENSION postgis_topology ADD function copytopology(character varying,character varying);
ALTER EXTENSION postgis_topology ADD function createtopogeom(character varying,integer,integer);
ALTER EXTENSION postgis_topology ADD function createtopogeom(character varying,integer,integer,topoelementarray);
ALTER EXTENSION postgis_topology ADD function createtopology(character varying);
ALTER EXTENSION postgis_topology ADD function createtopology(character varying,integer);
ALTER EXTENSION postgis_topology ADD function createtopology(character varying,integer,double precision);
ALTER EXTENSION postgis_topology ADD function createtopology(character varying,integer,double precision,boolean);
ALTER EXTENSION postgis_topology ADD function droptopogeometrycolumn(character varying,character varying,character varying);
ALTER EXTENSION postgis_topology ADD function droptopology(character varying);
ALTER EXTENSION postgis_topology ADD function equals(topogeometry,topogeometry);
ALTER EXTENSION postgis_topology ADD function geometry(topogeometry);
ALTER EXTENSION postgis_topology ADD function geometrytype(topogeometry);
ALTER EXTENSION postgis_topology ADD function getedgebypoint(character varying,geometry,double precision);
ALTER EXTENSION postgis_topology ADD function getfacebypoint(character varying,geometry,double precision);
ALTER EXTENSION postgis_topology ADD function getnodebypoint(character varying,geometry,double precision);
ALTER EXTENSION postgis_topology ADD function getnodeedges(character varying,integer);
ALTER EXTENSION postgis_topology ADD function getringedges(character varying,integer,integer);
ALTER EXTENSION postgis_topology ADD function gettopogeomelementarray(character varying,integer,integer);
ALTER EXTENSION postgis_topology ADD function gettopogeomelementarray(topogeometry);
ALTER EXTENSION postgis_topology ADD function gettopogeomelements(character varying,integer,integer);
ALTER EXTENSION postgis_topology ADD function gettopogeomelements(topogeometry);
ALTER EXTENSION postgis_topology ADD function gettopologyid(character varying);
ALTER EXTENSION postgis_topology ADD function gettopologyname(integer);
ALTER EXTENSION postgis_topology ADD function gettopologysrid(character varying);
ALTER EXTENSION postgis_topology ADD function intersects(topogeometry,topogeometry);
ALTER EXTENSION postgis_topology ADD function layertrigger();
ALTER EXTENSION postgis_topology ADD function polygonize(character varying);
ALTER EXTENSION postgis_topology ADD function postgis_topology_scripts_installed();
ALTER EXTENSION postgis_topology ADD function relationtrigger();
ALTER EXTENSION postgis_topology ADD function st_addedgemodface(character varying,integer,integer,geometry);
ALTER EXTENSION postgis_topology ADD function st_addedgenewfaces(character varying,integer,integer,geometry);
ALTER EXTENSION postgis_topology ADD function st_addisoedge(character varying,integer,integer,geometry);
ALTER EXTENSION postgis_topology ADD function st_addisonode(character varying,integer,geometry);
ALTER EXTENSION postgis_topology ADD function st_changeedgegeom(character varying,integer,geometry);
ALTER EXTENSION postgis_topology ADD function st_createtopogeo(character varying,geometry);
ALTER EXTENSION postgis_topology ADD function st_geometrytype(topogeometry);
ALTER EXTENSION postgis_topology ADD function st_getfaceedges(character varying,integer);
ALTER EXTENSION postgis_topology ADD function st_getfacegeometry(character varying,integer);
ALTER EXTENSION postgis_topology ADD function st_inittopogeo(character varying);
ALTER EXTENSION postgis_topology ADD function st_modedgeheal(character varying,integer,integer);
ALTER EXTENSION postgis_topology ADD function st_modedgesplit(character varying,integer,geometry);
ALTER EXTENSION postgis_topology ADD function st_moveisonode(character varying,integer,geometry);
ALTER EXTENSION postgis_topology ADD function st_newedgeheal(character varying,integer,integer);
ALTER EXTENSION postgis_topology ADD function st_newedgessplit(character varying,integer,geometry);
ALTER EXTENSION postgis_topology ADD function st_remedgemodface(character varying,integer);
ALTER EXTENSION postgis_topology ADD function st_remedgenewface(character varying,integer);
ALTER EXTENSION postgis_topology ADD function st_remisonode(character varying,integer);
ALTER EXTENSION postgis_topology ADD function st_removeisoedge(character varying,integer);
ALTER EXTENSION postgis_topology ADD function st_removeisonode(character varying,integer);
ALTER EXTENSION postgis_topology ADD function topoelementarray_agg(topoelement);
ALTER EXTENSION postgis_topology ADD function topoelementarray_append(topoelementarray,topoelement);
ALTER EXTENSION postgis_topology ADD function topogeo_addgeometry(character varying,geometry,double precision);
ALTER EXTENSION postgis_topology ADD function topogeo_addlinestring(character varying,geometry,double precision);
ALTER EXTENSION postgis_topology ADD function topogeo_addpoint(character varying,geometry,double precision);
ALTER EXTENSION postgis_topology ADD function topogeo_addpolygon(character varying,geometry,double precision);
ALTER EXTENSION postgis_topology ADD function topologysummary(character varying);
ALTER EXTENSION postgis_topology ADD function totopogeom(geometry,character varying,integer,double precision);
ALTER EXTENSION postgis_topology ADD function validatetopology(character varying);
ALTER EXTENSION postgis_topology ADD sequence topology_id_seq;
ALTER EXTENSION postgis_topology ADD table layer;
ALTER EXTENSION postgis_topology ADD table topology;
ALTER EXTENSION postgis_topology ADD type getfaceedges_returntype;
ALTER EXTENSION postgis_topology ADD type topoelement;
ALTER EXTENSION postgis_topology ADD type topoelementarray;
ALTER EXTENSION postgis_topology ADD type topogeometry;
ALTER EXTENSION postgis_topology ADD type validatetopology_returntype;
