 ALTER EXTENSION postgis_topology ADD cast(topology.topogeometry as geometry);
 ALTER EXTENSION postgis_topology ADD function topology._asgmledge(integer,integer,integer,geometry,regclass,text,integer,integer,text,integer);
 ALTER EXTENSION postgis_topology ADD function topology._asgmlface(text,integer,regclass,text,integer,integer,text,integer);
 ALTER EXTENSION postgis_topology ADD function topology._asgmlnode(integer,geometry,text,integer,integer,text,integer);
 ALTER EXTENSION postgis_topology ADD function topology._st_addfacesplit(character varying,integer,integer,boolean);
 ALTER EXTENSION postgis_topology ADD function topology._st_adjacentedges(character varying,integer,integer);
 ALTER EXTENSION postgis_topology ADD function topology._st_mintolerance(character varying,geometry);
 ALTER EXTENSION postgis_topology ADD function topology._st_mintolerance(geometry);
 ALTER EXTENSION postgis_topology ADD function topology._st_remedgecheck(character varying,integer,integer,integer,integer);
 ALTER EXTENSION postgis_topology ADD function topology.addedge(character varying,geometry);
 ALTER EXTENSION postgis_topology ADD function topology.addface(character varying,geometry,boolean);
 ALTER EXTENSION postgis_topology ADD function topology.addnode(character varying,geometry);
 ALTER EXTENSION postgis_topology ADD function topology.addnode(character varying,geometry,boolean,boolean);
 ALTER EXTENSION postgis_topology ADD function topology.addtopogeometrycolumn(character varying,character varying,character varying,character varying,character varying);
 ALTER EXTENSION postgis_topology ADD function topology.addtopogeometrycolumn(character varying,character varying,character varying,character varying,character varying,integer);
 ALTER EXTENSION postgis_topology ADD function topology.addtosearchpath(character varying);
 ALTER EXTENSION postgis_topology ADD function topology.asgml(topology.topogeometry);
 ALTER EXTENSION postgis_topology ADD function topology.asgml(topology.topogeometry,regclass);
 ALTER EXTENSION postgis_topology ADD function topology.asgml(topology.topogeometry,regclass,text);
 ALTER EXTENSION postgis_topology ADD function topology.asgml(topology.topogeometry,text);
 ALTER EXTENSION postgis_topology ADD function topology.asgml(topology.topogeometry,text,integer,integer);
 ALTER EXTENSION postgis_topology ADD function topology.asgml(topology.topogeometry,text,integer,integer,regclass);
 ALTER EXTENSION postgis_topology ADD function topology.asgml(topology.topogeometry,text,integer,integer,regclass,text);
 ALTER EXTENSION postgis_topology ADD function topology.asgml(topology.topogeometry,text,integer,integer,regclass,text,integer);
 ALTER EXTENSION postgis_topology ADD function topology.astopojson(topology.topogeometry,regclass);
 ALTER EXTENSION postgis_topology ADD function topology.cleartopogeom(topology.topogeometry);
 ALTER EXTENSION postgis_topology ADD function topology.copytopology(character varying,character varying);
 ALTER EXTENSION postgis_topology ADD function topology.createtopogeom(character varying,integer,integer);
 ALTER EXTENSION postgis_topology ADD function topology.createtopogeom(character varying,integer,integer,topology.topoelementarray);
 ALTER EXTENSION postgis_topology ADD function topology.createtopology(character varying);
 ALTER EXTENSION postgis_topology ADD function topology.createtopology(character varying,integer);
 ALTER EXTENSION postgis_topology ADD function topology.createtopology(character varying,integer,double precision);
 ALTER EXTENSION postgis_topology ADD function topology.createtopology(character varying,integer,double precision,boolean);
 ALTER EXTENSION postgis_topology ADD function topology.droptopogeometrycolumn(character varying,character varying,character varying);
 ALTER EXTENSION postgis_topology ADD function topology.droptopology(character varying);
 ALTER EXTENSION postgis_topology ADD function topology.equals(topology.topogeometry,topology.topogeometry);
 ALTER EXTENSION postgis_topology ADD function topology.geometry(topology.topogeometry);
 ALTER EXTENSION postgis_topology ADD function topology.geometrytype(topology.topogeometry);
 ALTER EXTENSION postgis_topology ADD function topology.getedgebypoint(character varying,geometry,double precision);
 ALTER EXTENSION postgis_topology ADD function topology.getfacebypoint(character varying,geometry,double precision);
 ALTER EXTENSION postgis_topology ADD function topology.getnodebypoint(character varying,geometry,double precision);
 ALTER EXTENSION postgis_topology ADD function topology.getnodeedges(character varying,integer);
 ALTER EXTENSION postgis_topology ADD function topology.getringedges(character varying,integer,integer);
 ALTER EXTENSION postgis_topology ADD function topology.gettopogeomelementarray(character varying,integer,integer);
 ALTER EXTENSION postgis_topology ADD function topology.gettopogeomelementarray(topology.topogeometry);
 ALTER EXTENSION postgis_topology ADD function topology.gettopogeomelements(character varying,integer,integer);
 ALTER EXTENSION postgis_topology ADD function topology.gettopogeomelements(topology.topogeometry);
 ALTER EXTENSION postgis_topology ADD function topology.gettopologyid(character varying);
 ALTER EXTENSION postgis_topology ADD function topology.gettopologyname(integer);
 ALTER EXTENSION postgis_topology ADD function topology.gettopologysrid(character varying);
 ALTER EXTENSION postgis_topology ADD function topology.intersects(topology.topogeometry,topology.topogeometry);
 ALTER EXTENSION postgis_topology ADD function topology.layertrigger();
 ALTER EXTENSION postgis_topology ADD function topology.polygonize(character varying);
 ALTER EXTENSION postgis_topology ADD function topology.postgis_topology_scripts_installed();
 ALTER EXTENSION postgis_topology ADD function topology.relationtrigger();
 ALTER EXTENSION postgis_topology ADD function topology.st_addedgemodface(character varying,integer,integer,geometry);
 ALTER EXTENSION postgis_topology ADD function topology.st_addedgenewfaces(character varying,integer,integer,geometry);
 ALTER EXTENSION postgis_topology ADD function topology.st_addisoedge(character varying,integer,integer,geometry);
 ALTER EXTENSION postgis_topology ADD function topology.st_addisonode(character varying,integer,geometry);
 ALTER EXTENSION postgis_topology ADD function topology.st_changeedgegeom(character varying,integer,geometry);
 ALTER EXTENSION postgis_topology ADD function topology.st_createtopogeo(character varying,geometry);
 ALTER EXTENSION postgis_topology ADD function topology.st_geometrytype(topology.topogeometry);
 ALTER EXTENSION postgis_topology ADD function topology.st_getfaceedges(character varying,integer);
 ALTER EXTENSION postgis_topology ADD function topology.st_getfacegeometry(character varying,integer);
 ALTER EXTENSION postgis_topology ADD function topology.st_inittopogeo(character varying);
 ALTER EXTENSION postgis_topology ADD function topology.st_modedgeheal(character varying,integer,integer);
 ALTER EXTENSION postgis_topology ADD function topology.st_modedgesplit(character varying,integer,geometry);
 ALTER EXTENSION postgis_topology ADD function topology.st_moveisonode(character varying,integer,geometry);
 ALTER EXTENSION postgis_topology ADD function topology.st_newedgeheal(character varying,integer,integer);
 ALTER EXTENSION postgis_topology ADD function topology.st_newedgessplit(character varying,integer,geometry);
 ALTER EXTENSION postgis_topology ADD function topology.st_remedgemodface(character varying,integer);
 ALTER EXTENSION postgis_topology ADD function topology.st_remedgenewface(character varying,integer);
 ALTER EXTENSION postgis_topology ADD function topology.st_remisonode(character varying,integer);
 ALTER EXTENSION postgis_topology ADD function topology.st_removeisoedge(character varying,integer);
 ALTER EXTENSION postgis_topology ADD function topology.st_removeisonode(character varying,integer);
 ALTER EXTENSION postgis_topology ADD function topology.st_simplify(topology.topogeometry,double precision);
 ALTER EXTENSION postgis_topology ADD function topology.topoelementarray_agg(topology.topoelement);
 ALTER EXTENSION postgis_topology ADD function topology.topoelementarray_append(topology.topoelementarray,topology.topoelement);
 ALTER EXTENSION postgis_topology ADD function topology.topogeo_addgeometry(character varying,geometry,double precision);
 ALTER EXTENSION postgis_topology ADD function topology.topogeo_addlinestring(character varying,geometry,double precision);
 ALTER EXTENSION postgis_topology ADD function topology.topogeo_addpoint(character varying,geometry,double precision);
 ALTER EXTENSION postgis_topology ADD function topology.topogeo_addpolygon(character varying,geometry,double precision);
 ALTER EXTENSION postgis_topology ADD function topology.topologysummary(character varying);
 ALTER EXTENSION postgis_topology ADD function topology.totopogeom(geometry,character varying,integer,double precision);
 ALTER EXTENSION postgis_topology ADD function topology.totopogeom(geometry,topology.topogeometry,double precision);
 ALTER EXTENSION postgis_topology ADD function topology.validatetopology(character varying);
 ALTER EXTENSION postgis_topology ADD sequence topology.topology_id_seq;
 ALTER EXTENSION postgis_topology ADD table topology.layer;
 ALTER EXTENSION postgis_topology ADD table topology.topology;
 ALTER EXTENSION postgis_topology ADD type topology.getfaceedges_returntype;
 ALTER EXTENSION postgis_topology ADD type topology.topoelement;
 ALTER EXTENSION postgis_topology ADD type topology.topoelementarray;
 ALTER EXTENSION postgis_topology ADD type topology.topogeometry;
 ALTER EXTENSION postgis_topology ADD type topology.validatetopology_returntype;

