coverage:
    status:
        project:
            default:
                threshold: 0.2%
        patch:
            default:
                threshold: 0.2%
comment: false
fixes:
    "liblwgeom/.libs/::liblwgeom/"
