#!/bin/sh
echo "Running OGC Regression Test..."
echo 
echo "       expected:'<'     obtained:'>'"
echo

DB=postgis_reg
createdb $DB > /dev/null
createlang plpgsql $DB > /dev/null
psql -f ../lwpostgis.sql $DB > /dev/null 2>&1
psql -tA < regress_ogc.sql $DB 2>&1 | grep -v INSERT > regress_ogc_out
diff regress_ogc_expected regress_ogc_out
sleep 1
dropdb $DB > /dev/null
