task:
  only_if: true
  name: FreeBSD
  alias: test-freebsd
  #env:
    #MAKE_FLAGS: -j 8

  install_script:
    - sed -i.bak -e 's,pkg+http://pkg.FreeBSD.org/\${ABI}/quarterly,pkg+http://pkg.FreeBSD.org/\${ABI}/latest,' /etc/pkg/FreeBSD.conf
    - ASSUME_ALWAYS_YES=yes pkg bootstrap -f
    - pkg install -y bison postgresql13-server gmake libxml2 autoconf automake libtool pkgconf iconv pcre proj gdal sfcgal geos libxslt cunit protobuf-c json-c postgresql13-contrib
    - projsync --system-directory --source-id us_noaa
    - projsync --system-directory --source-id ch_swisstopo

  patch_script:
    # will be removed
    - find . -name "*.pl" | xargs sed -i -r 's|/usr/bin/perl|/usr/bin/env perl|'
  build_script:
    - ./autogen.sh
    - ./configure PKG_CONFIG=/usr/local/bin/pkgconf CFLAGS="-isystem /usr/local/include -Wall -fno-omit-frame-pointer -Werror" LDFLAGS="-L/usr/local/lib" --with-libiconv-prefix=/usr/local --without-gui --without-interrupt-tests --with-topology --without-raster  --with-sfcgal=/usr/local/bin/sfcgal-config --with-address-standardizer --with-protobuf
    - service postgresql oneinitdb
    - service postgresql onestart
    - su postgres -c "createuser -s `whoami`"
    - gmake || { service postgresql onestop; exit 1;}
    - gmake check RUNTESTFLAGS="-v" || { service postgresql onestop; exit 1;}
    - gmake install || { service postgresql onestop; exit 1;}
    - gmake check RUNTESTFLAGS="-v --extension" || { service postgresql onestop; exit 1;}
    - gmake check RUNTESTFLAGS="-v --extension --dumprestore" || { service postgresql onestop; exit 1;}
    - service postgresql onestop

  freebsd_instance:
    cpu: 8
    memory: 24g
  matrix:
    # - name: 14-CURRENT
    #   freebsd_instance:
    #     image_family: freebsd-14-0-snap
    - name: 13.1-RELEASE
      freebsd_instance:
        image_family: freebsd-13-1
    - name: 12.3-RELEASE
      freebsd_instance:
        image_family: freebsd-12-3

