# See http://readme.drone.io/0.5/usage/overview

# See https://git.osgeo.org/gogs/postgis/postgis-docker
test-image: &test-image docker.kbt.io/postgis/build-test:trisquel2

matrix:
  PGVER:
    - 9.4
    - 9.5
    - 9.6
    - 10

pipeline:
  clone:
    image: plugins/git
    depth: 20
    recursive: false
  build:
    image: *test-image
    pull: true
    commands:
      - service postgresql start $PGVER
      - export PGPORT=`grep ^port /etc/postgresql/$PGVER/main/postgresql.conf | awk '{print $3}'`
      - export PATH=/usr/lib/postgresql/$PGVER/bin:$PATH
      - psql --version
      - ./autogen.sh
      - ./configure CFLAGS="-O0 -Wall -fno-omit-frame-pointer -Werror" --without-interrupt-tests
      - make
      # we should maybe wait for postgresql service to startup here...
      - psql -c "select version()" template1
      - make check RUNTESTFLAGS=-v
      - make install
      - utils/check_all_upgrades.sh
        `grep '^POSTGIS_' Version.config | cut -d= -f2 | paste -sd '.'`
