#---------------------------------------------------------------
# Configuration Directives
#---------------------------------------------------------------

#
# We recommend that you install the Proj4 and GEOS libraries
# referenced below to get the most use out of your PostGIS
# database.

#
# Set USE_PROJ to 1 for Proj4 reprojection support (recommended)
#
# Reprojection allows you to transform coordinate systems
# in the database with the Transform() function.
#
# Download from: http://www.remotesensing.org/proj
#
USE_PROJ ?= 0
PROJ_DIR ?= /usr/local

#
# Set USE_GEOS to 1 for GEOS spatial predicate and operator
# support (recommended).
# GEOS installation directory defaults to /usr/local,
# set GEOS_DIR environment variable to change it.
#
# GEOS allows you to do exact topological tests, such as
# Intersects() and Touches(), as well as geometry operations,
# such as Buffer(), GeomUnion() and Difference().
#
# Download from: http://geos.refractions.net
#
USE_GEOS ?= 0
GEOS_DIR ?= /usr/local

#
# Set USE_JTS to 1 if you have libjts installed. 
#
USE_JTS = 0
JTS_INCLUDES = jts
JTS_LIBDIR = jts


#
# Set USE_STATS to 1 for new GiST statistics collection support
# Note that this support requires additional columns in 
# GEOMETRY_COLUMNS, so see the list archives for info or
# install a fresh database using postgis.sql.
# This option is useless for builds against PGSQL>=80 (stats
# are always gathered in that case, and you don't need additional
# columns in geometry_columns).
#
USE_STATS=1

#
# Set AUTOCACHE_BBOX to 0 if you want finer control over
# bounding box computation and caching for your geometries.
# If you do, bbox computattion strategies are listed in
# the file lwgeom/BBOXCACHE_BEHAVIOURS, but don't expect
# them to be easy nor consistent.
#
AUTOCACHE_BBOX ?= 1

#
# Root of the PostgreSQL source tree 
# If you are not building from within postgresql 'contrib' directory
# set the PGSQL_SRC either below or in the environment (an absolute path).
#
# PGSQL_SRC=/usr/src/postgresql
PGSQL_SRC ?= ${PWD}/../..

#
# Set USE_ICONV to 1 if you want the loader (shp2pgsql)
# to support UTF-8 output.
#
USE_ICONV ?= 0

#
# Path to library (to be specified in CREATE FUNCTION queries)
# Defaults to $libdir.
# Set LPATH below or in the environment to change it.
#
# LPATH=/usr/src/postgis
LPATH ?= \$$libdir

#---------------------------------------------------------------
# END OF CONFIGURATION
#---------------------------------------------------------------

# Use JTS instead of GEOS if available
ifeq ($(USE_JTS),1)
	USE_GEOS=0
endif


subdir=contrib/postgis
top_builddir = ${PGSQL_SRC}
include $(top_builddir)/src/Makefile.global

#
# This needs to be defined after PGSQL Makefile.global
# has been sources as it redefines FLEX
#
ifeq ($(strip $(FLEX)),)
    FLEX = flex
endif
ifeq ($(strip $(YACC)),)
    YACC = yacc
endif

#---------------------------------------------------------------
# Test the version string and set the USE_VERSION macro
# appropriately.
#
ifneq ($(findstring 7.1,$(VERSION)),)
	USE_VERSION=71
else
	ifneq ($(findstring 7.2,$(VERSION)),)
		USE_VERSION=72
	else
		ifneq ($(findstring 7.3,$(VERSION)),)
			USE_VERSION=73
		else
			ifneq ($(findstring 7.4,$(VERSION)),)
				USE_VERSION=74
			else
				USE_VERSION=80
			endif
		endif
	endif
endif

