FROM kpengboy/trisquel
RUN apt-get update -qq && apt-get install -y \
          postgresql-9.3 postgresql-server-dev-9.3 \
          build-essential autoconf libtool libcunit1-dev \
          xsltproc docbook-xsl docbook-mathml dblatex \
          libproj-dev libgdal-dev libgeos-dev libjson0-dev

