all: 
	$(MAKE) -C postgis all
	$(MAKE) -C postgis_topology all

clean:
	$(MAKE) -C postgis clean
	$(MAKE) -C postgis_topology clean

install:
	$(MAKE) -C postgis install
	$(MAKE) -C postgis_topology install

check:
	echo "Nothing to check"

