.TH "postgis" "1" "" "" "PostGIS"
.SH "NAME"
.LP
postgis - postgis administration helper

.SH "SYNTAX"
.LP
postgis \fIcommand\fR [\fIarguments\fR]

.SH "DESCRIPTION"
.LP
The postgis script supports various commands to help with
administration of a PostGIS installation.

.SH "USAGE"
.LP
Usage information is printed when the script is invoked with no
arguments or with the \fBhelp\fR argument.

.SH "EXAMPLES"
.LP
An example command to check the status of PostGIS in the
\fBtemplate_postgis\fR database:

# \fBpostgis status template_postgis\fR

.SH "AUTHORS"
.LP
Originally written by Sandro Santilli <strk@kbt.io>.

More information is available at http://postgis.net
