SCRIPTS = \
	postgis_restore.pl \
	create_undef.pl \
	postgis_proc_upgrade.pl \
	profile_intersects.pl \
	test_estimation.pl \
	test_joinestimation.pl

all:
	chmod +x $(SCRIPTS)

# We don't install utils (why?)
install uninstall:

# There's nothing to clean
clean:
