/* h9_lattice_consts.h — AUTO-GENERATED by gen_h9_lattice_consts.py
 *                       DO NOT EDIT BY HAND.
 *
 * Generated: 2026-05-25 01:47
 *
 * Lookup tables for the analytic L5 lattice generator (port of
 * hhg9/h9/polygon.py:tri_grid / tri_mesh).  ~400 bytes total.
 *
 *   H9_KIDS[parent_mode][k] : child mode + (x, y) offset of child k
 *   H9_SV  [mode][vertex]   : unit-triangle vertex (x, y) for mode 0/1
 *
 * Iteration order over k matches Python H9R.downs / H9R.ups so that
 * `region_grid` produces identical output to the Python reference.
 *
 *   downs (mode 0 children) : [33, 37, 38, 42, 43, 53, 57, 58, 73]
 *   ups   (mode 1 children) : [22, 37, 38, 42, 52, 53, 57, 58, 62]
 */
#ifndef H9_LATTICE_CONSTS_H
#define H9_LATTICE_CONSTS_H

#include <cstdint>

namespace h9 {

struct LatticeKid {
    std::uint8_t mode;
    double off_x;
    double off_y;
};

inline constexpr LatticeKid H9_KIDS[2][9] = {
  { /* parent_mode = 0 (down) */
  /* k=0x21 */ { 0, -0.47140452079103173, 0.27216552697590868 },
  /* k=0x25 */ { 1, -0.23570226039551587, 0.13608276348795434 },
  /* k=0x26 */ { 0, 0, 0.27216552697590868 },
  /* k=0x2a */ { 1, 0.23570226039551587, 0.13608276348795434 },
  /* k=0x2b */ { 0, 0.47140452079103173, 0.27216552697590868 },
  /* k=0x35 */ { 0, -0.23570226039551587, -0.13608276348795434 },
  /* k=0x39 */ { 1, 0, -0.27216552697590868 },
  /* k=0x3a */ { 0, 0.23570226039551587, -0.13608276348795434 },
  /* k=0x49 */ { 0, 0, -0.54433105395181736 }
  },
  { /* parent_mode = 1 (up) */
  /* k=0x16 */ { 1, 0, 0.54433105395181736 },
  /* k=0x25 */ { 1, -0.23570226039551587, 0.13608276348795434 },
  /* k=0x26 */ { 0, 0, 0.27216552697590868 },
  /* k=0x2a */ { 1, 0.23570226039551587, 0.13608276348795434 },
  /* k=0x34 */ { 1, -0.47140452079103173, -0.27216552697590868 },
  /* k=0x35 */ { 0, -0.23570226039551587, -0.13608276348795434 },
  /* k=0x39 */ { 1, 0, -0.27216552697590868 },
  /* k=0x3a */ { 0, 0.23570226039551587, -0.13608276348795434 },
  /* k=0x3e */ { 1, 0.47140452079103173, -0.27216552697590868 }
  }
};

inline constexpr double H9_SV[2][3][2] = {
  { /* mode = 0 (down) unit-triangle vertices */
  { 0.70710678118654746, 0.40824829046386296 },
  { 0, -0.81649658092772592 },
  { -0.70710678118654746, 0.40824829046386296 }
  },
  { /* mode = 1 (up) unit-triangle vertices */
  { 0.70710678118654746, -0.40824829046386296 },
  { -0.70710678118654746, -0.40824829046386296 },
  { 0, 0.81649658092772592 }
  }
};

} // namespace h9

#endif /* H9_LATTICE_CONSTS_H */
