# This file should be installed in each
# language directory

local-all: local-html comments

local-html local-cheatsheets local-pdf local-chunked-html local-check: symlinks
	$(MAKE) $(patsubst local-%,%,$@)

symlinks:
	rm -f html; ln -s ../../html html
	rm -f xsl; ln -s $(srcdir)/../../xsl xsl

# for XML_SOURCES
include ../../Makefile

# XML gettext tools
PO2XML=po2xml

$(XML_SOURCES): %.xml: %.xml.po
	$(PO2XML) $(srcdir)/../../$@ $< > $@

