labels:
  platform: linux/amd64
when:
  event: [push, pull_request, tag]

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      depth: 50
      partial: false

steps:
  mingw-wine:
    image: debian:bookworm
    pull: true
    commands:
      - bash ci/dronie/postgis_mingw_wine.sh
