variables:
  test-image: &test-image docker.osgeo.org/postgis/build-test:trisquel3

clone:
  clone:
    image: woodpeckerci/plugin-git
    depth: 50

steps:

  autogen:
    image: *test-image
    pull: true
    commands:
      - ./autogen.sh

  regress-pg11:
    image: *test-image
    group: build
    commands:
      - PGVER=11 sh ci/dronie/postgis_regress.sh

  regress-pg12:
    image: *test-image
    group: build
    commands:
      - PGVER=12 sh ci/dronie/postgis_regress.sh

  regress-pg14:
    image: *test-image
    group: build
    commands:
      - PGVER=15 sh ci/dronie/postgis_regress.sh

  regress-pg15:
    image: *test-image
    group: build
    commands:
      - PGVER=15 sh ci/dronie/postgis_regress.sh
