matrix:
  PG_VERSION:
    - 15
    - 14
    - 12

steps:
  build:
    group: build
    image: docker.osgeo.org/postgis/build-test:trisquel3
    pull: true
    commands:
      - sh autogen.sh
      - PGVER=${PG_VERSION} sh ci/dronie/postgis_regress.sh
