labels:
  platform: linux/amd64
matrix:
  PG_VERSION:
    - 12
    - 11

steps:
  - name: build
    image: docker.osgeo.org/postgis/build-test:trisquel3
    commands:
      - sh autogen.sh
      - PGVER=${PG_VERSION} sh ci/dronie/postgis_regress.sh
