labels:
  platform: linux/amd64
when:
  event: [push, pull_request, tag]
matrix:
  PG_VERSION:
    - 15
    - 14
    - 12
    - 11

steps:
  - name: build
    image: repo.osgeo.org/postgis/build-test:trisquel3
    commands:
      - sh autogen.sh
      - PGVER=${PG_VERSION} sh ci/dronie/postgis_regress.sh
