name: Codespell Check

on:
  push:
    branches-ignore:
      - 'main'
  pull_request: ~

jobs:
  linux:

    runs-on: ubuntu-latest

    name: "CI Codespell"


    steps:

    - name: 'Check Out'
      uses: actions/checkout@v4

    - name: 'Install codespell'
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends libxml2-utils docbook-xml docbook-xsl docbook-xsl-ns xsltproc
        sudo pip install codespell

    - name: 'Build & Test'
      run: |
        codespell --version
        make -C doc comments
        ./utils/check_spelling.sh
