name: Codespell Check

on:
  push:
    branches-ignore:
      - 'main'
  pull_request: ~

jobs:
  linux:

    runs-on: ubuntu-latest

    name: "CI Codespell"


    steps:

    - name: 'Check Out'
      uses: actions/checkout@v4

    - name: 'Install codespell'
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          codespell \
          autoconf automake libtool pkg-config \
          libgeos-dev libproj-dev libxml2-dev \
          libxml2-utils docbook-xml docbook-xsl docbook-xsl-ns xsltproc

    - name: 'Build & Test'
      run: |
        codespell --version
        ./autogen.sh
        ./configure --without-raster --without-topology --without-sfcgal --without-json --without-protobuf
        make -C doc comments
        codespell --config .codespellrc .
