name: Contributor Credits

on:
  push:
    branches-ignore:
      - 'main'
  pull_request: ~

permissions:
  contents: read

jobs:
  contributor-credits:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Check Contributor Credits
        run: make check-contributor-credits
